FROM httpd:latest

#this section will be used for a production container. 
#COPY my_httpd_config.conf /usr/local/apache2/conf/httpd.conf


#docker build -t mjjohnson0417/httpd:latest .
#docker run -d --name jquery -p 8084:80 mjjohnson0417/httpd
#docker run -d --name jquery -p 8084:80 -v .:/usr/local/apache2/htdocs/:rw mjjohnson0417/httpd
#docker exec -it jquery sh
