FROM httpd:latest

#this section will be used for a production container. 
#COPY my_httpd_config.conf /usr/local/apache2/conf/httpd.conf

#docker run -d --name drumkit -p 8083:80 mjjohnson0417/httpd
#docker run -d --name drumkit -p 8083:80 -v .:/usr/local/apache2/htdocs/:rw mjjohnson0417/httpd
#docker exec -it drumkit sh
#docker run --rm httpd:latest cat /usr/local/apache2/conf/httpd.conf > my_httpd_config.conf
#this command lets you copy the httpd.conf file from inside the container using the standard #out to a file