FROM httpd:latest

#this section will be used for a production container. 
#COPY my_httpd_config.conf /usr/local/apache2/conf/httpd.conf
#COPY index.html /usr/local/apache2/htdocs/index.html
#$COPY styles.css /usr/local/apache2/htdocs/styles.css
#COPY game.js /usr/local/apache2/htdocs/game.js
#COPY sounds/ /usr/local/apache2/htdocs/sounds/
#ADD . /usr/local/apache2/htdocs/


#docker build -t mjjohnson0417/httpd:latest .
#docker run -d --name simongame -p 8085:80 mjjohnson0417/httpd
#docker run -d --name simongame -p 8085:80 -v .:/usr/local/apache2/htdocs/:rw mjjohnson0417/httpd
#docker exec -it simongame sh
#docker run --rm httpd:latest cat /usr/local/apache2/conf/httpd.conf > my_httpd_config.conf
#this command lets you copy the httpd.conf file from inside the container using the standard #out to a file